//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>
/// Permet de séparer complétement l'affichage du reste
/// 
/// </remarks>

#pragma once

class Adaptateur
{
	private :


	protected :


	public :


	private :


	protected :


	public :


}; 

