//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>
/// On affiche  un canevas qui contient des images
/// 
/// </remarks>
class Affichage
{
	private :


	protected :


	public :

		//object dossier image;
		//object canevas;

	private :


	protected :


	public :

		virtual void miseAjour();
		virtual void init();
		virtual void sendClickLancerDes();
		virtual void sendClickNbJoueurs();
		virtual void sendClickCase();
		virtual void sendClickChoisirPort();
		virtual void sendClickBateau();
		virtual void sendAngle();
		virtual void sendPuissance();

}; 

