//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "Etat.h"

class AttenteNbJoueurs : public Etat
{
	public :
		AttenteNbJoueurs();
		AttenteNbJoueurs(std::string mess);
		void execute();

}; 

