//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef ATTENTENBJOUEURS_H
#define ATTENTENBJOUEURS_H
#pragma once

#include <iostream>

#include "Etat.h"
#include "Facade.h"

using namespace std;

class AttenteNbJoueurs : public Etat
{
	protected :
		std::string message;
		Moteur* moteur;

	public :
		AttenteNbJoueurs() : message(""),moteur(NULL){};
		AttenteNbJoueurs(Moteur* mot) : message(""),moteur(mot){};
		~AttenteNbJoueurs();
		string getMessage() const;
		void execute();
		void setMessage(std::string mes);

}; 

inline string AttenteNbJoueurs::getMessage() const{
	return this->message;
}

#endif