//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include <iostream>

#include "Etat.h"
using namespace std;

class DLL AttenteNbJoueurs : public Etat
{
	protected :
		std::string message;
		Moteur* moteur;

	public :
		AttenteNbJoueurs() : message(""),moteur(NULL){};
		AttenteNbJoueurs(std::string mess,Moteur* mot) : message(mess),moteur(mot){};
		~AttenteNbJoueurs();
		string getMessage() const;
		void execute();

}; 

inline string AttenteNbJoueurs::getMessage() const{
	return this->message;
}

EXTERNC DLL AttenteNbJoueurs* AttenteNbJoueurs_New();
EXTERNC DLL void setNbJoueur(int a);