//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once
#ifndef CARAVELLE_H
#define CARAVELLE_H
#include "Bateau.h"

class Caravelle : public Bateau
{
	public :

		Caravelle(bool tres, int posx, int posy, int posPortx, int posPorty);
		Caravelle(const Bateau* bat);
		~Caravelle();

};

#endif