//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "Case.h"

class CaseNormale : public Case
{

	public :

		virtual bool estAuBord();
		inline bool getEstNavigable();
		class Etat& getEtat();

}; 

