//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef CASENORMALE_H
#define CASENORMALE_H

#pragma once
#include "Case.h"

class CaseNormale : public Case
{
	private :
		bool auBord;
	public :
		CaseNormale();
		CaseNormale(int haut,bool nav,bool aubord);
		//Faire un constructeur avec auBord, pour connaitre directement les cases au bord.
		bool estAuBord() const;
		bool getEstNavigable() const;
		int getEtat() const;

};

inline bool CaseNormale::estAuBord() const{
	return auBord;
}

#endif