//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "CaseNormale.h"
#include "Case.h"
#include"LancerDesDeplacement.h"



bool CaseNormale::estAuBord(){return false;} //On ne peut pas implémenter cette méthode, il faut la remonter dans PLateau.
		bool CaseNormale::getEstNavigable(){return this->estNavigable;}
		//Renvoie l'état dans lequel doit être le moteur après cett case !
		Etat CaseNormale::getEtat(){
			//Appeler le changement de joueur ?
			Etat e = LancerDesDeplacement();
			return e;
		}

