//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Case.h"
#include"LancerDesDeplacement.h"

class CaseTresor : public Case
{
	public :
		Etat CaseTresor::getEtat(){
			Etat e = LancerDesDeplacement();
			return e;
		}
}; 

