//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Etat.h"
#include "Case.h"

class CaseCanon : public Case
{
	private :


	protected :


	public :


	private :


	protected :


	public :

		Etat getEtat();

}; 

