//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Case.h"

class CasePort : public Case
{
	private :

		int couleur;

	protected :


	public :


	private :


	protected :


	public :

		inline int getCouleur(){return couleur;};
		bool estNavigable();
		Etat getEtat();

}; 

