//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once

#include "CasePort.h"

CasePort::CasePort(){
	this->CasePort::CasePort();
}

bool CasePort::getEstNavigable() const{
	return this->estNavigable; //Test si une case port est navigable.
			//Vérifier si un bateau peut aller sur un port qui n'a pas sa couleur.
}

int CasePort::getEtat() const{
	return 0;
}

