//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "Case.h"

class CasePort : public Case
{
	private :

		int couleur;

	public :

		inline int getCouleur(){return couleur;};
		bool getEstNavigable();
		Etat getEtat();

}; 

