//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once

#include "CaseNormale.h"
#include "Moteur.h"

bool CaseNormale::getEstNavigable() const{
	return this->estNavigable;
}

//Renvoie l'état dans lequel doit être le moteur après cette case !
int CaseNormale::getEtat() const{
	if(auBord){
		return Moteur::TIRCANONDUEL;
	}
	else{
		return Moteur::LANCERDESDEPLACEMENT;
	}
}