//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef CHOISIRPORT_H
#define CHOISIRPORT_H

#pragma once
#include "Etat.h"

class ChoisirPort : public Etat
{
	private :
		int portsLibres [4];

	protected :
		std::string message;
		Moteur* moteur;

	public :
		ChoisirPort() : message(""),moteur(NULL){};
		ChoisirPort(std::string mess,Moteur* mot) : message(mess),moteur(mot){};
		void execute();
		void setPortsLibres(int i);
		int* getPortsLibres();

}; 

inline int* ChoisirPort::getPortsLibres(){
	return this->portsLibres;
}

inline void ChoisirPort::setPortsLibres(int i){
	//a redef
}

#endif