//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef CHOISIRPORT_H
#define CHOISIRPORT_H

#pragma once
#include "Etat.h"

class ChoisirPort : public Etat
{
	private :
		int* portsLibres;

	protected :
		std::string message;
		Moteur* moteur;

	public :
		ChoisirPort();
		ChoisirPort(std::string mess,Moteur* mot);
		~ChoisirPort();
		void execute();
		void setPortsLibres(int i);
		int* getPortsLibres() const;
		bool estLibre(int i) const;
		std::string getMessage() const;

}; 

inline int* ChoisirPort::getPortsLibres() const{
	return this->portsLibres;
}

inline void ChoisirPort::setPortsLibres(int i){
	this->portsLibres[i-1] = 0;
}

inline std::string ChoisirPort::getMessage() const{
	return this->message;
}

#endif