//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class ChoisirPort : public Etat
{
	private :

		int[] portsLibres;

	protected :


	public :


	private :


	protected :


	public :

		override void execute();
		virtual void setPortsLibres(object int[] pl);
		virtual int[] getPortsLibres();

}; 

