//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#ifndef ETAT_H
#define ETAT_H
#include <string>
#include "Moteur.h"

class Etat
{
	public :

		virtual void execute() = 0;
		virtual void setMessage(std::string mes) = 0;
		//virtual std::string getMessage() const;

};

#endif