//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#define WANTDLLEXP

#ifdef WANTDLLEXP		//exportation dll 
		#define DLL  __declspec( dllexport ) 
		#define EXTERNC extern "C"
#else
		#define DLL		//standard
		#define EXTERNC 
		
#endif

#ifndef ETAT_H
#define ETAT_H

#pragma once

#include <string>
class Moteur;

class Etat
{
	public :
		virtual void execute();
		virtual void setMessage(std::string mes);
		virtual int* getPortsLibres() const;
		virtual std::string getMessage() const;
		//virtual std::string getMessage() const;

};

#endif