//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class Facade
{
	private :


	protected :


	public :


	private :


	protected :


	public :

		virtual bool activerDes();
		virtual bool activerCases();
		virtual bool activerPorts();
		virtual vector<Bateau> getBateaux();
		virtual string getMessage();
		virtual int[] getValeursDes();
		virtual bool afficheCurseurAngle();
		virtual bool afficheCurseurPuissance();
		virtual vector<pair<int,int>> getRelief();
		virtual bool afficheGagnant();
		virtual bool activerBateaux();
		virtual bool afficheTir();
		virtual void init();
		virtual int getNbJoueurs();
		virtual bool getAttenteNbJoueurs();
		virtual int[] getScores();
		virtual int getNbDes();
		virtual void setNbJoueurs(object int nb);
		virtual int[] getPortsLibres();
		virtual bool afficheBateaux();
		virtual bool afficheRelief();
		virtual bool afficheScores();
		virtual bool afficheDes();
		virtual void setAngle(object int angle);
		virtual void setPuissance(object int puissance);
		virtual void lancerDes();
		virtual void setCible(object int nb);
		virtual void setDeplacement(object int x, object int y);

}; 

