//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef FREGATE_H
#define FREGATE_H
#pragma once
#include "Bateau.h"

class Fregate : public Bateau
{
	public :
		Fregate();
		Fregate(bool tres, int posx, int posy, int posPortx, int posPorty);
		Fregate(const Bateau& bat);
		~Fregate();

}; 

#endif