//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class Joueur
{
	private :

		int score;
		int num;

	protected :


	public :


	private :


	protected :


	public :

		virtual int getScore();
		virtual void getNum : int();

}; 

