//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef JOUEUR_H
#define JOUEUR_H
#pragma once
#include "Bateau.h"
#include <map>

class Joueur
{
	private :
		std::map<int,int> score;
		int num;
		Bateau bateaux [2];
		
	public :
		Joueur();
		Joueur(int num,int nbBat,int nbPort1,int nbPort2=0);
		~Joueur();
		void degraderBateau(int x,int y);
		std::map<int,int> getScore() const;
		int getNum() const;

}; 

inline std::map<int,int> Joueur::getScore() const{
	return score;
}

inline int Joueur::getNum() const{
	return num;
}

#endif