//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef LANCERDESDEPLACEMENT_H
#define LANCERDESDEPLACEMENT_H
#pragma once

#include "LancerDes.h"
#include <vector>

class LancerDesDeplacement : public LancerDes
{
	private :
		std::vector<std::pair<int,int>> casesDeplacement;
	public :
		LancerDesDeplacement();
		LancerDesDeplacement(Moteur* mot);
		void execute();
		void calculCasesDeplacement(int scoreDe);
}; 

#endif