//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef LANCERDES_H
#define LANCERDES_H
#pragma once

#include "Etat.h"

class LancerDes : public Etat
{
	protected :
		std::string message;
		Moteur* moteur;

	public :
		LancerDes() : message(""),moteur(NULL){};
		LancerDes(Moteur* mot) : message(""),moteur(mot){};
		virtual void execute();
		virtual int* getCasesDeplacement() const;
		virtual int getNbCasesDeplacement() const;
		void setMessage(std::string mes);
		std::string getMessage() const;
}; 

inline void LancerDes::setMessage(std::string mes){
	this->message = mes;
}

inline std::string LancerDes::getMessage() const{
	return this->message;
}

#endif