//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class Moteur
{
	private :

		int nbJoueurs;
		int[] ordreJoueurs;
		int joueurCourant;

	protected :


	public :


	private :


	protected :


	public :

		virtual void setNbJoueurs(object int nb);
		virtual void setEtat(object Etat e);
		virtual void deplacerBateau(object Bateau b, object Case dest);
		virtual void execute();
		virtual int getNbJoueurs();

}; 

