//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "Case.h"
#include <vector>

class Navigation : public Etat
{
	private :


	protected :


	public :


	private :


	protected :


	public :

		void execute();
		std::vector<Case> getCasesAccessibles();
		void deplacer(int x, int y);
		void selectionBateauADeplacer();

}; 

