//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once
#include "Etat.h"
class PartieGagnee : public Etat
{
	private :
		int gagnant;

	protected :
		std::string message;
		Moteur* moteur;

	public :
		PartieGagnee() : message(""),moteur(NULL){};
		PartieGagnee(std::string mess,Moteur* mot) : message(mess),moteur(mot){};
		void afficherGagnant();
		void execute();
		int getGagnant();

}; 

