//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include "Plateau.h"

class Plateau
{
	
	Plateau::Plateau(int lo, int la){
			longueur=lo;
			largeur=la;
			tab_case = new Case[lo*la];
		}

	Case Plateau::getCase(int x, int y){
		return this->tab_case[x*longueur+y];
	}
	void Plateau::libereCase(int x,int y){
		
	}

	Etat Plateau::getEtat(int x, int y){
		;
	}

	bool Plateau::estNavigable(int x, int y){
		;
	}
	

}; 

