//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

class SetOrdreJoueurs : public LancerDes
{
	private :


	protected :


	public :


	private :


	protected :


	public :

		virtual void setOrdreJoueurs(object int j);
		virtual void lancerDes();
		override void execute();

}; 

