//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef SETORDREJOUEURS_H
#define SETORDREJOUEURS_H
#pragma once

#include "LancerDes.h"
#include <map>

class SetOrdreJoueurs : public LancerDes
{
	private :
		std::map<int,int> scoreDesJoueurs;
		int etatsuivant;

	public :
		SetOrdreJoueurs();
		SetOrdreJoueurs(Moteur* mot);
		void setOrdreJoueurs(int j);
		void execute();
		int getEtat() const;

};

inline int SetOrdreJoueurs::getEtat() const{
	return this->etatsuivant;
}

#endif