//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef TIRCANONDUEL_H
#define TIRCANONDUEL_H
#pragma once
#include "TirCanon.h"

class TirCanonDuel : public TirCanon
{
	private :
		bool premierTir;
		int joueurAttaquant;
		int joueurAttaque;
	public :
		TirCanonDuel() : TirCanon(),premierTir(true),joueurAttaquant(0){};
		TirCanonDuel(Moteur* mot) : TirCanon(mot),premierTir(true),joueurAttaquant(0){};
		void execute();
		void echangeDuel();
		int getEtat() const;
};

inline int TirCanonDuel::getEtat() const{
	return this->etatsuivant;
}

#endif