//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "TirerCanon.h"

class TirCanonUnique : public TirerCanon
{
	private :


	protected :


	public :


	private :


	protected :


	public :
		TirCanonUnique();
		void setCible(int num);
		void execute();

}; 

