//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class TirCanonDuel : public TirerCanon
{
	private :

		bool premierTir;

	protected :


	public :


	private :


	protected :


	public :

		virtual void choisirCible();
		virtual bool estPremierTir();
		override void execute();
		virtual void setJoueurOppose(object int num);
		virtual void echangeDuel();

}; 

