
package hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CircleFunctions", targetNamespace = "http://hello/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CircleFunctions {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://hello/", className = "hello.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://hello/", className = "hello.AddResponse")
    public double add(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getArea", targetNamespace = "http://hello/", className = "hello.GetArea")
    @ResponseWrapper(localName = "getAreaResponse", targetNamespace = "http://hello/", className = "hello.GetAreaResponse")
    public double getArea(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCircumference", targetNamespace = "http://hello/", className = "hello.GetCircumference")
    @ResponseWrapper(localName = "getCircumferenceResponse", targetNamespace = "http://hello/", className = "hello.GetCircumferenceResponse")
    public double getCircumference(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sub", targetNamespace = "http://hello/", className = "hello.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://hello/", className = "hello.SubResponse")
    public double sub(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mul", targetNamespace = "http://hello/", className = "hello.Mul")
    @ResponseWrapper(localName = "mulResponse", targetNamespace = "http://hello/", className = "hello.MulResponse")
    public double mul(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "div", targetNamespace = "http://hello/", className = "hello.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://hello/", className = "hello.DivResponse")
    public double div(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "calculatrice", targetNamespace = "http://hello/", className = "hello.Calculatrice")
    @ResponseWrapper(localName = "calculatriceResponse", targetNamespace = "http://hello/", className = "hello.CalculatriceResponse")
    public void calculatrice();

}
