//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "Etat.h"

class AttenteNbJoueurs : public Etat
{
	protected :
		std::string message;
		Moteur* moteur;

	public :
		AttenteNbJoueurs() : message(""),moteur(NULL){};
		AttenteNbJoueurs(std::string mess,Moteur* mot) : message(mess),moteur(mot){};
		void execute();

}; 