//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include <stdlib>
#include <pair>

class Bateau
{
	private :

		int nbDes;
		bool tresorABord;
		std::pair<int,int> position;
		std::pair<int,int> positionPort;

	protected :


	public :


	private :


	protected :


	public :

		virtual void deplacer(int x, int y);
		virtual bool tresorABord();
		virtual void setBateau(int bat);
		virtual void enleveTresor();
		virtual void donneTresor();
		virtual pair<int,int> getPosition();
		virtual pair<int,int> getPositionPort();

}; 

