//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "Bateau.h"

class Caravelle : public Bateau
{
	private :


	protected :


	public :


	private :


	protected :


	public :

		void donneTresor();
		void enleveTresor();

}; 

