//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef CASEPORT_H
#define CASEPORT_H

#pragma once
#include "Case.h"

class CasePort : public Case
{
	private :
		int couleur;

	public :
		CasePort() : Case(){};
		int getCouleur() const;
		bool getEstNavigable() const;
		bool estPort() const;
		int getEtat() const;

}; 

inline int CasePort::getCouleur() const{
	this->couleur;
}

inline bool CasePort::estPort() const{
	return true;
}

#endif