//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>typeCase renvoie le type de la case : Normale Port Canon Trésor</remarks>
class Case
{
	private :

		int hauteur;
		bool estNavigable;

	protected :


	public :


	private :


	protected :


	public :

		virtual bool estNavigable();
		virtual void libereCase();
		virtual int getHauteur();
		virtual Etat getEtat();

}; 

