//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef CASETRESOR_H
#define CASETRESOR_H

#pragma once
#include "Case.h"

class CaseTresor : public Case
{
	private :
		int nbTresors;

	public :
		CaseTresor();
		CaseTresor(int nbtres);
		int getNbTresors() const;
		int getEtat() const;
}; 

inline int CaseTresor::getNbTresors() const{
	return this->nbTresors;
}

#endif