//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


class CaseNormale : public Case
{

	public :

		virtual bool estAuBord();
		inline bool estNavigable();
		virtual Etat getEtat();

}; 

