//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include "Case.h"

class Case
{

	public :
		virtual void libereCase();
		virtual Etat getEtat();

}; 

