//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef CASECANON_H
#define CASECANON_H

#pragma once
#include "Case.h"

class CaseCanon : public Case
{
	public :
		CaseCanon();
		int getEtat() const;

}; 

#endif