//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class CasePort : public Case
{
	private :

		int couleur;

	protected :


	public :


	private :


	protected :


	public :

		virtual void getCouleur();
		override bool estNavigable();
		override Etat getEtat();

}; 

