//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef CASENORMALE_H
#define CASENORMALE_H

#pragma once
#include "Case.h"

class CaseNormale : public Case
{
	public :
		CaseNormale();
		bool estAuBord() const;
		bool getEstNavigable() const;
		int getEtat() const;

};

#endif