//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once

#include "CaseNormale.h"

CaseNormale::CaseNormale(){
	this->Case::Case();
}

bool CaseNormale::estAuBord() const{
	return false;
} //On ne peut pas implémenter cette méthode, il faut la remonter dans PLateau.

bool CaseNormale::getEstNavigable() const{
	return this->estNavigable;
}

//Renvoie l'état dans lequel doit être le moteur après cette case !
int CaseNormale::getEtat() const{
	//Appeler le changement de joueur ?
	return 0;
}

