//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once

#include "CasePort.h"
#include "Moteur.h"

CasePort::CasePort(){
	this->Case::Case();
}

bool CasePort::getEstNavigable() const{
	return this->estNavigable; //Test si une case port est navigable.
			//Vérifier si un bateau peut aller sur un port qui n'a pas sa couleur.
}

//Penser à vérifier le score du joueur car s'il a 3 trésors dans ce port, Etat PartieGagnee !
int CasePort::getEtat() const{
	return Moteur::LANCERDESDEPLACEMENT;
}