//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "CaseCanon.h"
#include "Moteur.h"

int CaseCanon::getEtat() const{
	return Moteur::TIRCANONUNIQUE;
}