//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "CaseTresor.h"

CaseTresor::CaseTresor(){
	this->Case::Case();
}

int CaseTresor::getEtat() const{	
	return 0;
}