//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include "Case.h"

class CaseTresor : public Case
{
	private :

		int nbTresors;




	public :

		inline int getNbTresors(){return nbTresors;}
		Etat getEtat();

}; 

