//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>typeCase renvoie le type de la case : Normale Port Canon Trésor</remarks>
#include "Etat.h"

class Case
{
	private :
		int hauteur;
		bool estNavigable;

	protected :


	public :


	private :


	protected :


	public :

		virtual inline bool getEstNavigable() const {return estNavigable;}
		virtual inline void setEstNavigable(bool b){estNavigable=b;}
		virtual void libereCase();
		inline int getHauteur(){return this->hauteur;}
		Etat getEtat();

};