//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once

#include "CaseNormale.h"

CaseNormale::CaseNormale(){
	this->Case::Case();
}

CaseNormale::CaseNormale(int haut,bool nav,bool aubord){
	this->Case::Case(haut,nav);
	this->auBord;
}

bool CaseNormale::getEstNavigable() const{
	return this->estNavigable;
}

//Renvoie l'état dans lequel doit être le moteur après cette case !
int CaseNormale::getEtat() const{
	if(auBord){
		return TIRCANONDUEL;
	}
	else{
		return LANCERDESDEPLACEMENT;
	}
}