//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef CHOISIRPORT_H
#define CHOISIRPORT_H

#pragma once
#include "Etat.h"

class ChoisirPort : public Etat
{
	private :
		int* portsLibres;
		int compteur;
		int port1;
		int port2;
		int etatsuivant;

	protected :
		std::string message;
		Moteur* moteur;

	public :
		ChoisirPort();
		ChoisirPort(Moteur* mot);
		~ChoisirPort();
		void execute();
		void setPortsLibres(int i);
		bool estLibre(int i) const;
		std::string getMessage() const;
		inline void setMessage(std::string mes){this->message = mes;};
		std::vector<int> getCasesActives() const;
		int getEtat() const;

};

inline void ChoisirPort::setPortsLibres(int i){
	this->portsLibres[i-1] = 0;
}

inline std::string ChoisirPort::getMessage() const{
	return this->message;
}

inline int ChoisirPort::getEtat() const{
	return this->etatsuivant;
}

#endif