//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class De
{
	private :

		int numero;

	protected :


	public :


	private :


	protected :


	public :

		virtual void lancerDe();
		virtual void getNum();

}; 

