//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef DE_H
#define DE_H
#pragma once

#include <stdlib.h>
#include <stdio.h>
#include <time.h>

class De
{
	private :
		int alea;

	public :
		De();
		De(int nb);
		int numero;
		/*~De();*/
		void lancerDe();
		int getNum() const;

}; 

inline int De::getNum() const{
	return numero;
}

#endif