//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include <stdlib.h>
#include <stdio.h>
#include <time.h>

class De
{
	private :
		int numero;

	public :
		De();
		De(int nb);
		~De();
		void lancerDe();
		int getNum() const;

}; 

inline int De::getNum() const{
	return numero;
}