//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class Etat
{
	private :


	protected :


	public :

		String message;

	private :


	protected :


	public :

		virtual void execute();
		virtual void setMessage(String mes);

}; 

