//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include <vector>
#include "Bateau.h"

class Facade
{
	private :


	protected :


	public :


	private :


	protected :


	public :

		bool activerDes();
		bool activerCases();
		bool activerPorts();
		std::vector<Bateau> getBateaux();
		std::string getMessage();
		int* getValeursDes();
		bool afficheCurseurAngle();
		bool afficheCurseurPuissance();
		std::vector<std::pair<int,int>> getRelief();
		bool afficheGagnant();
		bool activerBateaux();
		bool afficheTir();
		void init();
		int getNbJoueurs();
		bool getAttenteNbJoueurs();
		int* getScores();
		int getNbDes();
		void setNbJoueurs(int nb);
		int* getPortsLibres();
		bool afficheBateaux();
		bool afficheRelief();
		bool afficheScores();
		bool afficheDes();
		void setAngle(int angle);
		void setPuissance(int puissance);
		void lancerDes();
		void setCible(int nb);
		void setDeplacement(int x, int y);

}; 

