//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef FACADE_H
#define FACADE_H

#pragma once
#include <vector>
#include "Moteur.h"

class Facade
{
	private :
		Moteur* motor;

	public :
		Facade();
		~Facade();
		bool activerDes();
		bool activerCases();
		bool activerPorts();
		std::vector<Bateau> getBateaux();
		std::string getMessage();
		int* getValeursDes();
		bool afficheCurseurAngle();
		bool afficheCurseurPuissance();
		std::vector<std::pair<int,int>> getRelief();
		bool afficheGagnant();
		bool activerBateaux();
		bool afficheTir();
		void init();
		int getNbJoueurs();
		bool getAttenteNbJoueurs();
		int* getScores();
		int getNbDes();
		int* getPortsLibres();
		bool afficheBateaux();
		bool afficheRelief();
		bool afficheScores();
		bool afficheDes();
		void setAngle(int angle);
		void setPuissance(int puissance);
		void lancerDes();
		void setCible(int nb);
		void setDeplacement(int x, int y);

		void setNbJoueurs(int nb);
		void setClick(int x,int y);
};

inline void Facade::setNbJoueurs(int nb){
	this->motor->setNbJoueurs(nb);
}

#endif