//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef FREGATE_H
#define FREGATE_H
#pragma once
#include "Bateau.h"

class Fregate : public Bateau
{
	public :
		Fregate() : Bateau(){};
		Fregate(bool tres, int posx, int posy, int posPortx, int posPorty) : 
			Bateau(1,tres,posx,posy,posPortx,posPorty){};
		Fregate(const Bateau& bat);
		virtual ~Fregate();
		virtual int getNbDes() const;
};

inline int Fregate::getNbDes() const{
	return 1;
}

#endif