//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "LancerDes.h"

class LancerDesDeplacement : public LancerDes
{
	private :


	protected :


	public :


	private :


	protected :


	public :
		LancerDesDeplacement();
		LancerDesDeplacement(std::string mess,Moteur* mot);
		virtual void lancerDes();
		void execute();

}; 

