//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "Etat.h"

class LancerDes : public Etat
{
	protected :
		std::string message;
		Moteur* moteur;

	public :
		LancerDes() : message(""),moteur(NULL){};
		LancerDes(std::string mess,Moteur* mot) : message(mess),moteur(mot){};
		virtual void execute() = 0;

}; 

