//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once
#include "Bateau.h"
#include "Case.h"

class Moteur
{
	private :

		int nbJoueurs;
		int ordreJoueurs [4];
		int joueurCourant;

	protected :


	public :


	private :


	protected :


	public :

		virtual void setNbJoueurs(int nb);
		virtual void setEtat(Etat& e);
		virtual void deplacerBateau(Bateau& b, Case& dest);
		virtual void execute();
		int getNbJoueurs();

}; 

