//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class Navigation : public Etat
{
	private :


	protected :


	public :


	private :


	protected :


	public :

		override void execute();
		virtual vector<Case> getCasesAccessibles();
		virtual void deplacer(object int x, object int y);
		virtual void selectionBateauADeplacer();

}; 

