//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "Case.h"
#include <vector>

class Navigation : public Etat
{
	protected :
		std::string message;
		Moteur* moteur;

	public :
		Navigation() : message(""){};
		Navigation(std::string mess,Moteur* mot) : message(mess),moteur(mot){};
		void execute();
		std::vector<Case> getCasesAccessibles();
		void deplacer(int x, int y);
		void selectionBateauADeplacer();

}; 

