//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef NAVIGATION_H
#define NAVIGATION_H
#pragma once

#include "Case.h"
#include "Etat.h"
#include <vector>

class Navigation : public Etat
{
	protected :
		std::string message;
		Moteur* moteur;

	public :
		Navigation() : message(""),moteur(NULL){};
		Navigation(Moteur* mot) : message(""),moteur(mot){};
		void execute();
		void deplacer(int x, int y);
}; 

#endif