//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef PARTIEGAGNEE_H
#define PARTIEGAGNEE_H
#pragma once
#include "Etat.h"

class PartieGagnee : public Etat
{
	private :
		int gagnant;

	protected :
		std::string message;
		Moteur* moteur;

	public :
		PartieGagnee() : message(""),moteur(NULL){};
		PartieGagnee(Moteur* mot) : message(""),moteur(mot){};
		void afficherGagnant();
		void execute();
		int getGagnant();

}; 

#endif