//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class Plateau
{
	private :

		int longueur;
		int largeur;

	protected :


	public :


	private :


	protected :


	public :

		virtual int getLargeur();
		virtual int getLongueur();
		virtual Case getCase(object int x, object int y);
		virtual void libereCase(object int x, object int y);
		virtual Etat getEtat(object int x, object int y);
		virtual bool estNavigable(object int x, object inty);

}; 

