//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once
#include "Bateau.h"

class Radeau : public Bateau
{
	public :

		Radeau(int posx, int posy, int posPortx, int posPorty);
		Radeau(const Bateau* bat);
		~Radeau();

}; 

