//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef RADEAU_H
#define RADEAU_H

#pragma once
#include "Bateau.h"

class Radeau : public Bateau
{
	public :
		Radeau() : Bateau(){};
		Radeau(int posx, int posy, int posPortx, int posPorty) : 
			Bateau(1,false,posx,posy,posPortx,posPorty){};
		Radeau(const Bateau* bat);
		virtual ~Radeau();
		virtual bool donneTresor();
		virtual int getType() const;
};

inline bool Radeau::donneTresor(){
	return false;
}

#endif