//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "TirCanon.h"

class TirCanonUnique : public TirCanon
{
	private :

	public :
		TirCanonUnique();
		TirCanonUnique(std::string mess,Moteur* mot);
		void setCible(int num);
		void execute();

}; 

