//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef TIRCANON_H
#define TIRCANON_H
#pragma once
#include <vector>
#include "Etat.h"

class TirCanon : public Etat
{
	protected :
		std::string message;
		Moteur* moteur;

		int angle;
		int puissance;
		int bateauAttaquant;
		int bateauAttaque;
		bool tirReussi;
		std::pair<int,int> positionAttaquant;
		std::pair<int,int> positionAttaque;

	public :
		TirCanon();
		TirCanon(Moteur* mot);
		void execute();
		void setAngle(int ang);
		void setPuissance(int puis);
		void setCible(int num);
		void faireTir();
		bool getTirReussi();
		void effectuerChangements();
		int* calculerRelief();
		bool tirFini();
		std::vector<std::pair<int,int>> calculerTir();
}; 

inline void TirCanon::setAngle(int ang){
	this->angle = ang;
}

inline void TirCanon::setPuissance(int puis){
	this->puissance = puis;
}
#endif