//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once
#include "TirCanon.h"

class TirCanonDuel : public TirCanon
{
	private :

		bool premierTir;

	protected :


	public :


	private :


	protected :


	public :

		virtual void choisirCible();
		virtual bool estPremierTir();
		void execute();
		virtual void setJoueurOppose(int num);
		virtual void echangeDuel();

}; 

