//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class TirerCanon : public Etat
{
	private :

		int angle;
		int puissance;
		int joueurAttaquant;
		int joueurAttaque;
		bool tirReussi;
		pair<int,int> positionAttaquant;
		pair<int,int> positionAttaque;

	protected :


	public :


	private :


	protected :


	public :

		override void execute();
		virtual void setAngle(object int ang);
		virtual void setPuissance(object int puis);
		virtual void setCible(object int num);
		virtual void faireTir();
		virtual bool tirReussi();
		virtual void effectuerChangements();
		virtual int[] calculerRelief();
		virtual bool tirFini();
		virtual vector<pair<int,int>> calculerTir();

}; 

