//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef TIRCANONDUEL_H
#define TIRCANONDUEL_H
#pragma once
#include "TirCanon.h"

class TirCanonDuel : public TirCanon
{
	private :

		bool premierTir;

	public :
		TirCanonDuel();
		TirCanonDuel(Moteur* mot);
		bool estPremierTir() const;
		void execute();
		void echangeDuel();

}; 

inline bool TirCanonDuel::estPremierTir() const{
	return this->premierTir;
}

#endif