//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class TirCanonUnique : public TirerCanon
{
	private :


	protected :


	public :


	private :


	protected :


	public :

		override void setCible(object int num);
		override void execute();

}; 

