
package net.webservicex;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SunSetRiseService", targetNamespace = "http://www.webserviceX.NET/", wsdlLocation = "http://www.webservicex.net/sunsetriseservice.asmx?WSDL")
public class SunSetRiseService
    extends Service
{

    private final static URL SUNSETRISESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(net.webservicex.SunSetRiseService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = net.webservicex.SunSetRiseService.class.getResource(".");
            url = new URL(baseUrl, "http://www.webservicex.net/sunsetriseservice.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.webservicex.net/sunsetriseservice.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SUNSETRISESERVICE_WSDL_LOCATION = url;
    }

    public SunSetRiseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SunSetRiseService() {
        super(SUNSETRISESERVICE_WSDL_LOCATION, new QName("http://www.webserviceX.NET/", "SunSetRiseService"));
    }

    /**
     * 
     * @return
     *     returns SunSetRiseServiceSoap
     */
    @WebEndpoint(name = "SunSetRiseServiceSoap")
    public SunSetRiseServiceSoap getSunSetRiseServiceSoap() {
        return super.getPort(new QName("http://www.webserviceX.NET/", "SunSetRiseServiceSoap"), SunSetRiseServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SunSetRiseServiceSoap
     */
    @WebEndpoint(name = "SunSetRiseServiceSoap")
    public SunSetRiseServiceSoap getSunSetRiseServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserviceX.NET/", "SunSetRiseServiceSoap"), SunSetRiseServiceSoap.class, features);
    }

}
