//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class CaseTresor : public Case
{
	private :

		int nbTresors;

	protected :


	public :


	private :


	protected :


	public :

		virtual void getNbTresors : int();
		override Etat getEtat();

}; 

