//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class PartieGagnee : public Etat
{
	private :

		int gagnant;

	protected :


	public :


	private :


	protected :


	public :

		void afficherGagnant();
		override void execute();
		int getGagnant();

}; 

